# Verificar se o identificador já foi declarado no mesmo escopo
4000 ::= 4001 2000 # SINGLE_DECLARATION ::= TYPE id

# Verificar se algum dos identificadores já foi declarado no mesmo escopo
4002 ::= 4003 3008 2000 # MULTIPLE_DECLARATION ::= DECLARATION , id
4002 ::= 4004 3008 2000 # MULTIPLE_DECLARATION ::= DECLARATION_ASSIGNMENT, id

4004 ::= 4003 3011 4005 # DECLARATION_ASSIGNMENT ::= DECLARATION = EXPRESSION

4003 ::= 4000 # DECLARATION ::= SINGLE_DECLARATION
4003 ::= 4002 # DECLARATION ::= MULTIPLE_DECLARATION
4003 ::= 4006 # DECLARATION ::= FUNCTION_DECLARATION

4007 ::= 1031 # TYPE_PRIMITIVE ::= void
4007 ::= 1017 # TYPE_PRIMITIVE ::= int
4007 ::= 1008 # TYPE_PRIMITIVE ::= double
4007 ::= 1012 # TYPE_PRIMITIVE ::= float
4007 ::= 1003 # TYPE_PRIMITIVE ::= char
4007 ::= 1023 # TYPE_PRIMITIVE ::= signed
4007 ::= 1030 # TYPE_PRIMITIVE ::= unsigned
4007 ::= 1022 # TYPE_PRIMITIVE ::= short
4007 ::= 1018 # TYPE_PRIMITIVE ::= long

# Verificar a compatibilidade de tipos
4001 ::= 4007 # TYPE ::= TYPE_PRIMITIVE
4001 ::= 4001 4001 # TYPE ::= TYPE TYPE

# Verificar se a declaração possui um único identificador
4006 ::= 4003 3004 3005 # FUNCTION_DECLARATION ::= DECLARATION ( )

4008 ::= 3009 # STATEMENT ::= ;
4008 ::= 4003 3009 # STATEMENT ::= DECLARATION ;
4008 ::= 4004 3009 # STATEMENT ::= DECLARATION_ASSIGNMENT ;
4008 ::= 4006 3009 # STATEMENT ::= FUNCTION_DECLARATION ;
4008 ::= 4008 4008 # STATEMENT ::= STATEMENT STATEMENT

4005 ::= 2000 # EXPRESSION ::= id
4005 ::= 2001 # EXPRESSION ::= number_literal
4005 ::= 2002 # EXPRESSION ::= string_literal
4005 ::= 2003 # EXPRESSION ::= char_literal
4005 ::= 3004 4005 3005 # EXPRESSION ::= ( EXPRESSION )