# Verificar se o identificador já foi declarado no mesmo escopo
SINGLE_DECLARATION ::= TYPE id

# Verificar se algum dos identificadores já foi declarado no mesmo escopo
MULTIPLE_DECLARATION ::= DECLARATION , id
MULTIPLE_DECLARATION ::= DECLARATION_ASSIGNMENT, id

DECLARATION_ASSIGNMENT ::= DECLARATION = EXPRESSION

DECLARATION ::= SINGLE_DECLARATION
DECLARATION ::= MULTIPLE_DECLARATION
DECLARATION ::= FUNCTION_DECLARATION

TYPE_PRIMITIVE ::= void
TYPE_PRIMITIVE ::= int
TYPE_PRIMITIVE ::= double
TYPE_PRIMITIVE ::= float
TYPE_PRIMITIVE ::= char
TYPE_PRIMITIVE ::= signed
TYPE_PRIMITIVE ::= unsigned
TYPE_PRIMITIVE ::= short
TYPE_PRIMITIVE ::= long

# Verificar a compatibilidade de tipos
TYPE ::= TYPE_PRIMITIVE
TYPE ::= TYPE TYPE

# Verificar se a declaração possui um único identificador
FUNCTION_DECLARATION ::= DECLARATION ( )

STATEMENT ::= ;
STATEMENT ::= DECLARATION ;
STATEMENT ::= DECLARATION_ASSIGNMENT ;
STATEMENT ::= FUNCTION_DECLARATION ;
STATEMENT ::= STATEMENT STATEMENT

EXPRESSION ::= id
EXPRESSION ::= number_literal
EXPRESSION ::= string_literal
EXPRESSION ::= char_literal
EXPRESSION ::= ( EXPRESSION )